# Generated by Django 4.1 on 2022-09-05 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('bond_id', models.UUIDField(default=uuid.UUID('493f5906-ade4-44fe-a1b7-170d68324a20'), editable=False, primary_key=True, serialize=False)),
                ('bond_code', models.CharField(max_length=255)),
                ('coupon_percent', models.IntegerField()),
                ('coupon_price', models.IntegerField()),
                ('yield_to_maturity', models.IntegerField()),
                ('stock_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.UUIDField(default=uuid.UUID('d306a465-c2c1-4f67-9c7e-65b7d65a7d3f'), editable=False, primary_key=True, serialize=False)),
                ('currensy_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.UUIDField(default=uuid.UUID('19c93c90-5c2a-41cd-a291-0b1e909fdffd'), editable=False, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=255)),
                ('purchase_price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('day_of_purchase', models.DateField()),
                ('cost', models.IntegerField()),
                ('broker_fee', models.IntegerField()),
                ('asset_portfolio_id', models.IntegerField()),
                ('currensy_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.currency')),
            ],
        ),
        migrations.CreateModel(
            name='TargetForDate',
            fields=[
                ('target_for_date_id', models.UUIDField(default=uuid.UUID('1bfe3df9-72d4-4a5d-9d35-9ca0f747625d'), editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1063)),
                ('target_date', models.DateField()),
                ('stock_id', models.ManyToManyField(blank=True, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('share_id', models.UUIDField(default=uuid.UUID('ad454fa6-ee49-4444-b55b-1414162612f1'), editable=False, primary_key=True, serialize=False)),
                ('share_code', models.CharField(max_length=255)),
                ('stock_id', models.ManyToManyField(blank=True, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='PriceTarget',
            fields=[
                ('price_target_id', models.UUIDField(default=uuid.UUID('4a0eaf3b-71f1-438b-b080-744d3ffaf32a'), editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1063)),
                ('target_price', models.IntegerField()),
                ('stock_id', models.ManyToManyField(blank=True, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('etf_id', models.UUIDField(default=uuid.UUID('42792360-9249-49e8-85b1-e71fe3d1cffe'), editable=False, primary_key=True, serialize=False)),
                ('etf_code', models.CharField(max_length=255)),
                ('stock_id', models.ManyToManyField(blank=True, to='stocks.stock')),
            ],
        ),
    ]
