# Generated by Django 4.1 on 2022-09-08 01:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_start_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bond',
            name='stock_id',
        ),
        migrations.RemoveField(
            model_name='etf',
            name='stock_id',
        ),
        migrations.RemoveField(
            model_name='pricetarget',
            name='stock_id',
        ),
        migrations.RemoveField(
            model_name='share',
            name='stock_id',
        ),
        migrations.RemoveField(
            model_name='targetfordate',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='bond_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.bond'),
        ),
        migrations.AddField(
            model_name='stock',
            name='etf_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.etf'),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_target_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.pricetarget'),
        ),
        migrations.AddField(
            model_name='stock',
            name='share_is',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.share'),
        ),
        migrations.AddField(
            model_name='stock',
            name='target_for_date_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.targetfordate'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='bond_id',
            field=models.UUIDField(default=uuid.UUID('1d8a75ab-4d4f-406b-b984-c54ba9d6a053'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_id',
            field=models.UUIDField(default=uuid.UUID('ba24737f-3958-4839-ad47-577ef7918146'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etf',
            name='etf_id',
            field=models.UUIDField(default=uuid.UUID('3af681fc-376f-434c-b782-1f7e7321095b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricetarget',
            name='price_target_id',
            field=models.UUIDField(default=uuid.UUID('dfabe122-04a5-4082-8e74-3b7544ceb8f9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_id',
            field=models.UUIDField(default=uuid.UUID('a10977b5-c6e4-407b-9408-1105d2571cb4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_id',
            field=models.UUIDField(default=uuid.UUID('c5ec358e-3385-464e-96fb-ed2c58dcc9a5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetfordate',
            name='target_for_date_id',
            field=models.UUIDField(default=uuid.UUID('ca263c29-cbbe-4cb2-8039-f88a246ddfdb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
